import { MetricCard, PageHeader, StatusPill } from "@/components/AppPrimitives";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowUpRight, CircleDollarSign, Package, PackageCheck, ReceiptText } from "lucide-react";
import { useLocation } from "wouter";

const money = (value: number | string) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(Number(value));

export default function Dashboard() {
  const [, navigate] = useLocation();
  const { data, isLoading, isError, refetch } = trpc.insights.dashboard.useQuery();
  return <div className="space-y-7"><PageHeader eyebrow="Operations at a glance" title="Good morning, keep the floor moving." description="A clear view of inventory health, sales activity, and the work that needs attention today." actions={<><Button variant="outline" onClick={() => navigate("/products")} className="h-10 rounded-xl border-[#dfe7df] bg-white text-[#405147] hover:bg-[#f7faf7]">Browse inventory</Button><Button onClick={() => navigate("/sales")} className="h-10 rounded-xl bg-[#1f5f48] px-4 hover:bg-[#174c39]"><ReceiptText className="mr-2 h-4 w-4"/>Record a sale</Button></>} />
    {isError ? <section role="alert" className="flex flex-col gap-3 rounded-2xl border border-[#f0d5d1] bg-[#fff8f7] p-4 text-sm text-[#8f443b] sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">Operational summary is temporarily unavailable.</p><p className="mt-1 text-xs text-[#a2635d]">Your data was not changed. Retry the request to refresh the dashboard.</p></div><Button size="sm" variant="outline" onClick={() => refetch()} className="w-fit rounded-lg border-[#eac7c2] bg-white text-[#934940] hover:bg-[#fff2f0]">Retry dashboard</Button></section> : null}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <MetricCard label="Product catalogue" value={isLoading ? "—" : String(data?.totalProducts ?? 0)} detail="Active SKUs under management" icon={<Package className="h-5 w-5"/>} />
      <MetricCard label="Sales revenue" value={isLoading ? "—" : money(data?.totalSalesRevenue ?? 0)} detail={`${data?.transactionCount ?? 0} completed transactions`} accent="emerald" icon={<CircleDollarSign className="h-5 w-5"/>} />
      <MetricCard label="Low-stock watch" value={isLoading ? "—" : String(data?.lowStockCount ?? 0)} detail={`At or below the ${data?.lowStockThreshold ?? 0}-unit alert line`} accent={data?.lowStockCount ? "amber" : "ink"} icon={<AlertTriangle className="h-5 w-5"/>} />
      <MetricCard label="Today’s pace" value={isLoading ? "—" : String(data?.transactionCount ?? 0)} detail="Transactions in the current view" accent="ink" icon={<ReceiptText className="h-5 w-5"/>} />
    </section>
    <section className="grid gap-5 xl:grid-cols-[1.3fr_.9fr]">
      <div className="surface-card overflow-hidden"><div className="flex items-center justify-between px-5 py-5"><div><h2 className="font-display text-lg font-semibold tracking-tight text-[#26372f]">Recent transactions</h2><p className="mt-1 text-xs text-[#758079]">Latest recorded sales activity</p></div><Button variant="ghost" onClick={() => navigate("/sales")} className="h-8 rounded-lg text-xs font-semibold text-[#317458] hover:bg-[#edf6ef]">View ledger <ArrowUpRight className="ml-1.5 h-3.5 w-3.5"/></Button></div>
        <div className="divide-y divide-[#edf0eb]">{isLoading ? <div className="p-5 text-sm text-[#78847c]">Loading transactions…</div> : data?.recentTransactions.length ? data.recentTransactions.map(sale => <div key={sale.id} className="flex items-center justify-between gap-4 px-5 py-4"><div className="min-w-0"><p className="font-semibold text-[#37473e]">{sale.reference}</p><p className="mt-1 truncate text-xs text-[#7a857e]">{sale.customerName || "Walk-in customer"} · {new Date(sale.saleDate).toLocaleDateString()}</p></div><p className="font-display text-base font-semibold tracking-tight text-[#1d6047]">{money(sale.totalAmount)}</p></div>) : <div className="flex min-h-42 flex-col items-center justify-center px-6 py-7 text-center"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#e8f4eb] text-[#28704f]"><ReceiptText className="h-4 w-4"/></div><p className="mt-3 text-sm font-semibold text-[#405047]">Start the day’s ledger</p><p className="mt-1 text-xs text-[#7b867f]">Record a completed sale to see live transaction activity here.</p><Button variant="ghost" onClick={() => navigate("/sales")} className="mt-2 h-8 rounded-lg text-xs font-semibold text-[#357657] hover:bg-[#edf6ef]">Record a sale <ArrowUpRight className="ml-1.5 h-3.5 w-3.5"/></Button></div>}</div>
      </div>
      <aside className="surface-card overflow-hidden"><div className="flex items-center justify-between px-5 py-5"><div><h2 className="font-display text-lg font-semibold tracking-tight text-[#26372f]">Needs attention</h2><p className="mt-1 text-xs text-[#758079]">Inventory at the alert threshold</p></div><Button variant="ghost" onClick={() => navigate("/products")} className="h-8 rounded-lg text-xs font-semibold text-[#317458] hover:bg-[#edf6ef]">Review</Button></div>
        <div className="divide-y divide-[#edf0eb]">{isLoading ? <div className="p-5 text-sm text-[#78847c]">Checking stock…</div> : data?.lowStockProducts.length ? data.lowStockProducts.map(product => <div key={product.id} className="flex items-center justify-between gap-3 px-5 py-3.5"><div className="min-w-0"><p className="truncate text-sm font-semibold text-[#37473e]">{product.name}</p><p className="mt-1 text-[11px] font-medium tracking-wide text-[#849087]">{product.sku}</p></div><StatusPill tone={product.quantity === 0 ? "danger" : "warning"}>{product.quantity} left</StatusPill></div>) : <div className="flex min-h-42 flex-col items-center justify-center px-6 py-7 text-center"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#e8f4eb] text-[#28704f]"><PackageCheck className="h-4 w-4"/></div><p className="mt-3 text-sm font-semibold text-[#405047]">Inventory is in good shape</p><p className="mt-1 text-xs text-[#7b867f]">Every item is currently above the configured alert line.</p></div>}</div>
      </aside>
    </section>
  </div>;
}
