import { EmptyTable, PageHeader, StatusPill, TablePagination } from "@/components/AppPrimitives";
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowDownUp, Edit3, PackagePlus, Search, SlidersHorizontal, Trash2, X } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

const money = (value: number | string) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(value));
const blank = { name: "", sku: "", category: "", price: "", quantity: "0", supplierId: "" };

export default function Products() {
  const { user } = useAuth(); const canManage = user?.role === "admin" || user?.role === "manager";
  const [search, setSearch] = useState(""); const [category, setCategory] = useState(""); const [lowStockOnly, setLowStockOnly] = useState(false); const [page, setPage] = useState(1); const [sortBy, setSortBy] = useState<"createdAt"|"name"|"sku"|"category"|"price"|"quantity">("createdAt"); const [sortDirection, setSortDirection] = useState<"asc"|"desc">("desc"); const [form, setForm] = useState(blank); const [editing, setEditing] = useState<any>(null); const [open, setOpen] = useState(false);
  const input = useMemo(() => ({ page, pageSize: 10, search: search || undefined, category: category || undefined, lowStockOnly, sortBy, sortDirection }), [page, search, category, lowStockOnly, sortBy, sortDirection]);
  const { data, isLoading } = trpc.products.list.useQuery(input); const { data: categories } = trpc.products.categories.useQuery(); const { data: suppliers } = trpc.suppliers.list.useQuery({ page: 1, pageSize: 100, sortBy: "name", sortDirection: "asc" }); const utils = trpc.useUtils();
  const create = trpc.products.create.useMutation({ onSuccess: () => { toast.success("Product created"); close(); utils.products.list.invalidate(); utils.insights.dashboard.invalidate(); }, onError: error => toast.error(error.message) }); const update = trpc.products.update.useMutation({ onSuccess: () => { toast.success("Product updated"); close(); utils.products.list.invalidate(); }, onError: error => toast.error(error.message) }); const remove = trpc.products.remove.useMutation({ onSuccess: () => { toast.success("Product removed"); utils.products.list.invalidate(); utils.insights.dashboard.invalidate(); }, onError: error => toast.error(error.message) });
  function close() { setOpen(false); setEditing(null); setForm(blank); }
  function submit(e: React.FormEvent) { e.preventDefault(); const payload = { name: form.name, sku: form.sku, category: form.category, price: Number(form.price), supplierId: form.supplierId ? Number(form.supplierId) : null }; if (editing) update.mutate({ id: editing.id, ...payload }); else create.mutate({ ...payload, quantity: Number(form.quantity) }); }
  function toggleSort(key: typeof sortBy) { if (sortBy === key) setSortDirection(current => current === "asc" ? "desc" : "asc"); else { setSortBy(key); setSortDirection("asc"); } setPage(1); }
  return <div className="space-y-7"><PageHeader eyebrow="Catalogue" title="Product inventory" description="Manage products, supplier links, pricing, and the stock levels that keep your operation moving." actions={canManage ? <Button onClick={() => setOpen(true)} className="h-10 rounded-xl bg-[#1f5f48] hover:bg-[#174c39]"><PackagePlus className="mr-2 h-4 w-4"/>Add product</Button> : undefined}/>
    <section className="surface-card overflow-hidden"><div className="flex flex-col gap-3 border-b border-[#edf0eb] p-4 lg:flex-row lg:items-center lg:justify-between"><div className="relative max-w-md flex-1"><Search className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-[#849087]"/><input value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder="Search name, SKU, or category" className="field-input pl-9" /></div><div className="flex flex-wrap gap-2"><select value={category} onChange={e => { setCategory(e.target.value); setPage(1); }} className="field-select w-auto"><option value="">All categories</option>{categories?.map(item => <option key={item.category} value={item.category}>{item.category}</option>)}</select><Button variant={lowStockOnly ? "default" : "outline"} onClick={() => { setLowStockOnly(value => !value); setPage(1); }} className={`h-10 rounded-xl ${lowStockOnly ? "bg-[#b76b12] hover:bg-[#97550c]" : "border-[#dfe7df] bg-white"}`}><SlidersHorizontal className="mr-2 h-4 w-4"/>Low stock</Button></div></div>
      <div className="overflow-x-auto"><table className="data-table w-full min-w-[900px]"><thead><tr>{[["name", "Product"], ["sku", "SKU"], ["category", "Category"], ["price", "Unit price"], ["quantity", "Available"]].map(([key, label]) => <th key={key}><button onClick={() => toggleSort(key as typeof sortBy)} className="inline-flex items-center gap-1 hover:text-[#426c57]">{label}{sortBy === key ? <ArrowDownUp className="h-3 w-3"/> : null}</button></th>)}<th>Supplier</th><th>Status</th>{canManage ? <th className="text-right">Actions</th> : null}</tr></thead><tbody>{isLoading ? <tr><td colSpan={canManage ? 8 : 7} className="py-12 text-center">Loading products…</td></tr> : data?.items.length ? data.items.map(product => <tr key={product.id}><td><p className="font-semibold text-[#35453c]">{product.name}</p><p className="mt-0.5 text-xs text-[#8a938e]">Updated {new Date(product.updatedAt).toLocaleDateString()}</p></td><td className="font-mono text-xs font-medium">{product.sku}</td><td>{product.category}</td><td className="font-medium text-[#334a3d]">{money(product.price)}</td><td className="font-semibold text-[#3d5046]">{product.quantity}</td><td>{product.supplierName || <span className="text-[#9ba39e]">Unassigned</span>}</td><td><StatusPill tone={product.quantity === 0 ? "danger" : product.isLowStock ? "warning" : "success"}>{product.quantity === 0 ? "Out of stock" : product.isLowStock ? "Low stock" : "Healthy"}</StatusPill></td>{canManage ? <td><div className="flex justify-end gap-1"><Button size="icon" variant="ghost" className="h-8 w-8 rounded-lg text-[#527060]" onClick={() => { setEditing(product); setForm({ name: product.name, sku: product.sku, category: product.category, price: String(product.price), quantity: String(product.quantity), supplierId: product.supplierId ? String(product.supplierId) : "" }); setOpen(true); }}><Edit3 className="h-4 w-4"/></Button><Button size="icon" variant="ghost" className="h-8 w-8 rounded-lg text-[#aa4b42]" onClick={() => { if (confirm(`Remove ${product.name}? This cannot be undone.`)) remove.mutate({ id: product.id }); }}><Trash2 className="h-4 w-4"/></Button></div></td> : null}</tr>) : <tr><td colSpan={canManage ? 8 : 7} className="p-0"><EmptyTable title="No products found" description="Try adjusting the search or filters, or add the first product to your catalogue."/></td></tr>}</tbody></table></div>{data ? <TablePagination page={data.page} pageCount={data.pageCount} total={data.total} pageSize={data.pageSize} onPageChange={setPage}/> : null}</section>
    {open ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#102b24]/35 p-4 backdrop-blur-sm"><form onSubmit={submit} className="surface-card max-h-[90vh] w-full max-w-lg overflow-y-auto p-6"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#4b7f67]">Catalogue</p><h2 className="mt-1 font-display text-xl font-semibold tracking-tight">{editing ? "Edit product" : "Add product"}</h2></div><Button type="button" size="icon" variant="ghost" onClick={close} className="h-8 w-8 rounded-lg"><X className="h-4 w-4"/></Button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="field-label">Product name</span><input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} className="field-input"/></label><label><span className="field-label">SKU</span><input required value={form.sku} onChange={e => setForm({ ...form, sku: e.target.value })} className="field-input"/></label><label><span className="field-label">Category</span><input required value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} className="field-input"/></label><label><span className="field-label">Unit price</span><input required min="0" step="0.01" type="number" value={form.price} onChange={e => setForm({ ...form, price: e.target.value })} className="field-input"/></label>{!editing ? <label><span className="field-label">Initial quantity</span><input required min="0" type="number" value={form.quantity} onChange={e => setForm({ ...form, quantity: e.target.value })} className="field-input"/></label> : null}<label className="sm:col-span-2"><span className="field-label">Supplier</span><select value={form.supplierId} onChange={e => setForm({ ...form, supplierId: e.target.value })} className="field-select"><option value="">No supplier assigned</option>{suppliers?.items.map(supplier => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select></label></div><div className="mt-7 flex justify-end gap-2"><Button type="button" variant="outline" onClick={close} className="rounded-xl border-[#dfe7df]">Cancel</Button><Button disabled={create.isPending || update.isPending} className="rounded-xl bg-[#1f5f48] hover:bg-[#174c39]">{editing ? "Save changes" : "Create product"}</Button></div></form></div> : null}
  </div>;
}
